version: '3.9'

services:

  sanitizer:
    build: ./sanitizer
    container_name: sanitizer_service
    ports:
      - "8000:8000"
    networks:
      - llm_net

  orchestrator:
    build: ./orchestrator
    container_name: orchestrator_service
    depends_on:
      - sanitizer
    ports:
      - "7000:7000"
    networks:
      - llm_net

  guardrail:
    build: ./guardrail
    container_name: guardrail_service
    ports:
      - "6000:6000"
    networks:
      - llm_net

  bias_guardrail:
    build: ./bias_guardrail
    container_name: bias_guardail_service
    ports:
      - "5000:5000"
    networks:
      - llm_net

  output_guardrail:
    build: ./output_guardrail
    container_name: output_guardrail_service
    ports:
      - "4000:4000"
    networks:
      - llm_net

networks:
  llm_net:
    driver: bridge